### ISSUE TITLE
Stripe not Working with Live Test, See details below...

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#16]
![stripeflowissue](https://user-images.githubusercontent.com/34143768/36923727-0f318bf6-1e21-11e8-914b-fc78826b7f14.jpeg)

**Comment by urentmellc** [comment]
Looks like when your setting up a Stripe Account as a User it is oriented for businesses only not individual as it asks for co website, etc... we need the users to be able to incorporate this or find another solution other than allowing users to use stripe.. maybe another payment gateway???

**Comment by Jayantapixel** [comment]
You need to be more detailed i this. Please answer following question:
1. Send me the renter and owner details (user/pass) which you have used for testing.
2. I feel you have chosen Strip as payment option when you are going to pay
3. I understand, the owner has already saved his Stripe account from whom you are going to rent an item. Otherwise its wont work.
4. In stripe, you need to pay through Credit card only.

Please response this quickly.
