### ISSUE TITLE
~PRIORITY~Maps Not Working Anymore on Any Listings~, This Worked Before! Please Fix Now

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#30]
The maps are not showing on any listing now. This was working before. We need to have this showing on all listings. Please fix this problem asap. I have investor meetings on tuesday and the site needs to show this. 
<img width="1440" alt="screen shot 2018-03-17 at 11 12 12 am" src="https://user-images.githubusercontent.com/34143768/37558645-152c1166-29d4-11e8-95ff-9ff34070dcf8.png">

**Comment by Jayantapixel** [comment]
I have checked and its working most. Few may not work if you give wrong address. Check attached
![map2](https://user-images.githubusercontent.com/35031627/37567604-6774ce42-2aef-11e8-93e7-43778471f0ee.png)
![map1](https://user-images.githubusercontent.com/35031627/37567605-67ca808a-2aef-11e8-9ac9-3bfafdbbad2f.png)

**Comment by urentmellc** [comment]
Jayanta, I will require the full map features to work not part of it.. All needs to work so please have this handled as well by my Monday. Thank you.

**Comment by Jayantapixel** [comment]
Full map feature is working but if you don't put address, then map will not show and this was happening in your system. But from now onwards, it will not happen, since without admin approval, no item will be shown in the public site and admin need to check if all information about items are there in the listing.

**Comment by urentmellc** [comment]
please ensure the new api was added to the site and advise.
