### ISSUE TITLE
~PRIORITY, ASAP, USER CONTACTED ME AND COULD NOT LOGIN AND PICS NOT UNLOADING AND SAME NOTICE CODE ERROR~ 

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#43]
ALL THE ISSUES YOU CLAIM TO HAVE FIXED A NEW USER HAD SO MANY ISSUES WILL PROVIDE THEM BELOW. 

1) CANT UPLOAD PHOTOS
2) NO EMAIL VERIFICATION 
3) ERROR AGAIN IN CODE STATING MAKE MODEL ETC

THESE ARE NOT NEW ISSUES, THEY WERE APPARENTLY CORRECTED BUT THEY HAVE NOT BEEN. I NEED THESE THINGS RESOLVED IMMEDIATELY AND TESTED NUMEROUS TIMES BEFORE YOU TELL ME ITS BEEN RESOLVED.

**Comment by Jayantapixel** [comment]
1. We have corrected the upload photo issue and described in other point.
2. On verification email, we have created a new user (indrapixel / Indrajit@123) and got the verification email (screenshot attached). So sometime it may be customer email client issue so its going his Spam folder. So they need to check.
3. Make, Model has some saving issues on database when editing the list. Its resolved now. Earlier issue was in validation and its saving fine when adding a new listing. We thought, if addition working then no need to check edit since its a similar code but only need to update instead append.

Please re-check and let me know if you facing any issue.
![submit-free-listing-register](https://user-images.githubusercontent.com/35031627/38250794-52bfa78a-376d-11e8-8ae0-45577fe9236d.png)

**Comment by Jayantapixel** [comment]
Please close it. Same issues opened in multiple number which increasing the open issue.
