### ISSUE TITLE
~CONTENT MANAGEMENT PAGE EDITING IN ADMIN PANEL~

### ISSUE THREAD

**Issue by urentmellc** [pixelphpdev/urentme#52]
HAVING THE SAME ISSUES AS THE HOW IT WORKS IN THESE PAGES, PLEASE FIX THE SCRIPT EDITOR IN THESE PAGES SO I CAN MAKE ADJUSTMENTS MYSELF. I ALSO WANT THE ABILITY TO CHANGE CHANGE THE FONT SIZE FROM THE ADMIN PANEL. THANK YOU. 

<img width="1440" alt="screen shot 2018-04-08 at 7 15 17 pm" src="https://user-images.githubusercontent.com/34143768/38476194-47f39832-3b61-11e8-9854-2ef9483fe9ed.png">

**Comment by urentmellc** [comment]
The main Heading is smaller and I cant change this... i need the ability to edit all font and type in the admin panel for all...
<img width="1440" alt="screen shot 2018-04-08 at 7 33 52 pm" src="https://user-images.githubusercontent.com/34143768/38476659-d5802a42-3b63-11e8-955a-72bd6edc03f2.png">

**Comment by Jayantapixel** [comment]
On Payment option page, we have made it slightly different design. But now made it simple so you can make changes as your own. Please check.

**Comment by Jayantapixel** [comment]
Regarding styles on editor, since its a 3rd party editor so we cant change anything there. But I found there is option to make the font size bigger and other different style. Instead putting test as Normal, you can put it as Heading1, Heading2, heading3 etc where font sizes are different. Whatever styles are there you can use ONLY those.
![image](https://user-images.githubusercontent.com/35031627/38489293-8b4a4110-3c03-11e8-8063-0bf21953aee8.png)

**Comment by urentmellc** [comment]
Please fix this as it was previously you cannot see it something was done and now it looks horrible. see pic above that is what it must be.... 

<img width="1440" alt="screen shot 2018-04-09 at 6 49 44 am" src="https://user-images.githubusercontent.com/34143768/38501584-3a012f3a-3bc2-11e8-89e9-c98da0a6e6f9.png">

**Comment by Jayantapixel** [comment]
This is done yesterday only. Thanks
